#!/bin/bash
# Quick Reference: Common Commands for Generative Model Analysis

echo "==============================================="
echo "GENERATIVE MODEL ANALYSIS - QUICK REFERENCE"
echo "==============================================="
echo ""

echo "1. REPAIR MALFORMED OUTPUT FILE"
echo "   python ~/life-sequencing-dutch/pop2vec/llm/scripts/repair_generative_output.py \\"
echo "       /projects/0/prjs1589/stonybrook/llm/gen_out/INPUT.txt \\"
echo "       /projects/0/prjs1589/stonybrook/llm/gen_out/OUTPUT_repaired.txt"
echo ""

echo "2. ANALYZE TOKENS (STATISTICS)"
echo "   python ~/life-sequencing-dutch/pop2vec/llm/scripts/analyze_generative_output.py \\"
echo "       /projects/0/prjs1589/stonybrook/llm/gen_out/INPUT_repaired.txt \\"
echo "       --output_dir /projects/0/prjs1589/stonybrook/llm/gen_out/analysis/"
echo ""

echo "3. FULL ANALYSIS (REPAIR + ANALYZE)"
echo "   cd ~/life-sequencing-dutch/pop2vec/llm/scripts"
echo "   ./run_full_analysis.sh \\"
echo "       /projects/0/prjs1589/stonybrook/llm/gen_out/INPUT.txt \\"
echo "       /projects/0/prjs1589/stonybrook/llm/gen_out/analysis_output"
echo ""

echo "4. EVALUATE MODEL (DISTRIBUTIONS)"
echo "   python ~/life-sequencing-dutch/pop2vec/llm/scripts/evaluate_generative_model.py \\"
echo "       --generated_h5 /path/to/generated.h5 \\"
echo "       --real_h5 /projects/0/prjs1589/stonybrook/fake_data_v0/step5/encoding=nomlm/encoded.h5 \\"
echo "       --vocab_path /projects/0/prjs1589/stonybrook/fake_data_v0/step5/vocab_v0.csv \\"
echo "       --output_dir /projects/0/prjs1589/stonybrook/llm/gen_out/evaluation/ \\"
echo "       --max_sequences 1000"
echo ""

echo "5. GENERATE 1000 LIVES"
echo "   cd ~/life-sequencing-dutch"
echo "   python -m pop2vec.llm.src.new_code.generative_infer \\"
echo "       --hparams pop2vec/llm/src/hparams/snellius/generate_1000_lives.txt"
echo ""

echo "6. GENERATE COUPLES + CHECK FOR BABIES"
echo "   python -m pop2vec.llm.src.new_code.generative_infer \\"
echo "       --hparams pop2vec/llm/src/hparams/snellius/generate_couples_babies.txt"
echo ""

echo "==============================================="
echo "FILES CREATED:"
echo "==============================================="
echo "Scripts:"
echo "  ~/life-sequencing-dutch/pop2vec/llm/scripts/repair_generative_output.py"
echo "  ~/life-sequencing-dutch/pop2vec/llm/scripts/analyze_generative_output.py"
echo "  ~/life-sequencing-dutch/pop2vec/llm/scripts/evaluate_generative_model.py"
echo "  ~/life-sequencing-dutch/pop2vec/llm/scripts/run_full_analysis.sh"
echo ""
echo "Configs:"
echo "  ~/life-sequencing-dutch/pop2vec/llm/src/hparams/snellius/generate_1000_lives.txt"
echo "  ~/life-sequencing-dutch/pop2vec/llm/src/hparams/snellius/generate_couples_babies.txt"
echo ""
echo "Documentation:"
echo "  ~/life-sequencing-dutch/pop2vec/llm/scripts/README_ANALYSIS.md"
echo "  ~/GENERATIVE_ANALYSIS_SUMMARY.md"
echo ""

echo "==============================================="
echo "BUG FIX:"
echo "==============================================="
echo "✅ Fixed utils.py (lines 475-490)"
echo "   - Removed max_per_line parameter"
echo "   - Now outputs ONE LINE per sequence"
echo "   - No more split sequences!"
echo ""
