#!/usr/bin/env python3
"""
Timeline and Visualization Generator
======================================
Generates HTML reports with visualizations from analysis results.
"""

import os
import json
import argparse
from datetime import datetime
from collections import defaultdict


HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SLURM Log Analysis Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               background: #f5f5f5; color: #333; line-height: 1.6; }}
        .container {{ max-width: 1400px; margin: 0 auto; padding: 20px; }}
        h1 {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
             color: white; padding: 30px; text-align: center; margin-bottom: 30px;
             border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
        h2 {{ color: #667eea; margin: 30px 0 15px; border-bottom: 2px solid #667eea; 
             padding-bottom: 10px; }}
        h3 {{ color: #764ba2; margin: 20px 0 10px; }}
        .card {{ background: white; border-radius: 10px; padding: 20px; margin-bottom: 20px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                      gap: 20px; margin-bottom: 30px; }}
        .stat-card {{ background: white; border-radius: 10px; padding: 20px; text-align: center;
                     box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .stat-value {{ font-size: 2.5em; font-weight: bold; color: #667eea; }}
        .stat-label {{ color: #666; margin-top: 5px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #667eea; color: white; }}
        tr:hover {{ background: #f8f9fa; }}
        .bar {{ height: 20px; background: linear-gradient(90deg, #667eea, #764ba2);
               border-radius: 10px; transition: width 0.3s; }}
        .bar-container {{ background: #e0e0e0; border-radius: 10px; overflow: hidden; }}
        .chart {{ height: 300px; display: flex; align-items: flex-end; gap: 2px; 
                 padding: 10px; background: #f8f9fa; border-radius: 10px; }}
        .chart-bar {{ flex: 1; background: linear-gradient(180deg, #667eea, #764ba2);
                     border-radius: 5px 5px 0 0; min-width: 20px; position: relative; }}
        .chart-bar:hover {{ opacity: 0.8; }}
        .chart-bar span {{ position: absolute; bottom: -20px; left: 50%; transform: translateX(-50%);
                          font-size: 10px; white-space: nowrap; }}
        .tooltip {{ position: absolute; bottom: 100%; left: 50%; transform: translateX(-50%);
                   background: #333; color: white; padding: 5px 10px; border-radius: 5px;
                   font-size: 12px; white-space: nowrap; opacity: 0; transition: opacity 0.2s; }}
        .chart-bar:hover .tooltip {{ opacity: 1; }}
        .legend {{ display: flex; flex-wrap: wrap; gap: 15px; margin: 15px 0; }}
        .legend-item {{ display: flex; align-items: center; gap: 5px; }}
        .legend-color {{ width: 15px; height: 15px; border-radius: 3px; }}
        .success {{ color: #28a745; }}
        .warning {{ color: #ffc107; }}
        .danger {{ color: #dc3545; }}
        footer {{ text-align: center; padding: 30px; color: #666; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 SLURM Log Analysis Report</h1>
        <p style="text-align: center; color: #666; margin-bottom: 30px;">
            Generated on {generated_date}
        </p>
        
        {content}
        
        <footer>
            <p>Generated by SLURM Log Analyzer</p>
        </footer>
    </div>
</body>
</html>
'''


def load_json_file(filepath):
    """Load JSON file if it exists."""
    if os.path.exists(filepath):
        with open(filepath, 'r') as f:
            return json.load(f)
    return None


def generate_stats_cards(data):
    """Generate overview statistics cards."""
    if not data:
        return ""
    
    total_files = len(data)
    with_timing = sum(1 for d in data if d.get('duration_seconds'))
    completed = sum(1 for d in data if d.get('completed_normally'))
    total_hours = sum(d.get('duration_seconds', 0) for d in data) / 3600
    
    return f'''
    <div class="stats-grid">
        <div class="stat-card">
            <div class="stat-value">{total_files:,}</div>
            <div class="stat-label">Total Log Files</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{with_timing:,}</div>
            <div class="stat-label">With Timing Info</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{completed:,}</div>
            <div class="stat-label">Completed Normally</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{total_hours:,.0f}h</div>
            <div class="stat-label">Total Compute Time</div>
        </div>
    </div>
    '''


def generate_monthly_chart(monthly_data):
    """Generate monthly activity chart."""
    if not monthly_data:
        return ""
    
    max_count = max(d['count'] for d in monthly_data.values()) if monthly_data else 1
    
    bars = ""
    for month, data in sorted(monthly_data.items()):
        height = (data['count'] / max_count) * 250
        bars += f'''
        <div class="chart-bar" style="height: {height}px;">
            <span class="tooltip">{month}: {data['count']} jobs, {data['total_duration_hours']:.0f}h</span>
            <span>{month[-2:]}</span>
        </div>
        '''
    
    return f'''
    <h2>📅 Monthly Activity</h2>
    <div class="card">
        <div class="chart">{bars}</div>
        <p style="text-align: center; margin-top: 30px; color: #666;">Month</p>
    </div>
    '''


def generate_job_type_table(job_type_data):
    """Generate job type statistics table."""
    if not job_type_data:
        return ""
    
    rows = ""
    for jtype, data in sorted(job_type_data.items(), key=lambda x: -x[1]['count']):
        completion_class = 'success' if data['completion_rate'] > 80 else ('warning' if data['completion_rate'] > 50 else 'danger')
        bar_width = min(data['completion_rate'], 100)
        rows += f'''
        <tr>
            <td><strong>{jtype}</strong></td>
            <td>{data['count']:,}</td>
            <td>{data['total_duration_hours']:.1f}h</td>
            <td>{data['avg_duration_minutes']:.1f} min</td>
            <td>
                <div class="bar-container">
                    <div class="bar" style="width: {bar_width}%"></div>
                </div>
                <span class="{completion_class}">{data['completion_rate']:.0f}%</span>
            </td>
        </tr>
        '''
    
    return f'''
    <h2>📊 Jobs by Type</h2>
    <div class="card">
        <table>
            <thead>
                <tr>
                    <th>Job Type</th>
                    <th>Count</th>
                    <th>Total Time</th>
                    <th>Avg Duration</th>
                    <th>Completion Rate</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
    </div>
    '''


def generate_model_size_chart(job_type_data):
    """Generate model size distribution from job type data."""
    model_counts = defaultdict(int)
    
    for jtype, data in job_type_data.items():
        for model, count in data.get('model_sizes', {}).items():
            model_counts[model] += count
    
    if not model_counts:
        return ""
    
    max_count = max(model_counts.values())
    
    bars = ""
    for model, count in sorted(model_counts.items(), key=lambda x: -x[1]):
        height = (count / max_count) * 200
        bars += f'''
        <div class="chart-bar" style="height: {height}px; min-width: 60px;">
            <span class="tooltip">{model}: {count} jobs</span>
            <span>{model}</span>
        </div>
        '''
    
    return f'''
    <h2>🤖 Jobs by Model Size</h2>
    <div class="card">
        <div class="chart" style="height: 250px;">{bars}</div>
    </div>
    '''


def generate_pretrain_analysis(pretrain_data):
    """Generate pretraining analysis section."""
    if not pretrain_data:
        return ""
    
    by_model = pretrain_data.get('by_model_size', {})
    if not by_model:
        return ""
    
    rows = ""
    for model, stats in sorted(by_model.items()):
        rows += f'''
        <tr>
            <td><strong>{model}</strong></td>
            <td>{stats['count']}</td>
            <td>{stats.get('avg_duration_hours', 0):.1f}h</td>
            <td>{stats.get('total_duration_hours', 0):.1f}h</td>
            <td>{stats.get('max_epochs', 0)}</td>
        </tr>
        '''
    
    summary = pretrain_data.get('summary', {})
    
    return f'''
    <h2>🏋️ Pretraining Analysis</h2>
    <div class="card">
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value">{summary.get('total_jobs', 0)}</div>
                <div class="stat-label">Total Pretrain Jobs</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{summary.get('completed', 0)}</div>
                <div class="stat-label">Completed</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{summary.get('forced_stopped', 0)}</div>
                <div class="stat-label">Force Stopped</div>
            </div>
        </div>
        
        <h3>By Model Size</h3>
        <table>
            <thead>
                <tr>
                    <th>Model</th>
                    <th>Count</th>
                    <th>Avg Duration</th>
                    <th>Total Time</th>
                    <th>Max Epochs</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
    </div>
    '''


def generate_eval_analysis(eval_data):
    """Generate evaluation analysis section."""
    if not eval_data:
        return ""
    
    by_task = eval_data.get('by_task', {})
    
    rows = ""
    sorted_tasks = sorted(by_task.items(), key=lambda x: -x[1]['total'])[:15]
    for task, stats in sorted_tasks:
        success_rate = (stats['with_results'] / stats['total'] * 100) if stats['total'] else 0
        success_class = 'success' if success_rate > 80 else ('warning' if success_rate > 50 else 'danger')
        rows += f'''
        <tr>
            <td><strong>{task}</strong></td>
            <td>{stats['total']}</td>
            <td class="{success_class}">{stats['with_results']}</td>
            <td>{success_rate:.0f}%</td>
        </tr>
        '''
    
    return f'''
    <h2>📈 Evaluation Results</h2>
    <div class="card">
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value">{eval_data.get('total_eval_logs', 0)}</div>
                <div class="stat-label">Total Eval Jobs</div>
            </div>
            <div class="stat-card">
                <div class="stat-value success">{eval_data.get('with_results', 0)}</div>
                <div class="stat-label">With Results</div>
            </div>
            <div class="stat-card">
                <div class="stat-value danger">{eval_data.get('without_results', 0)}</div>
                <div class="stat-label">Without Results</div>
            </div>
        </div>
        
        <h3>Top Tasks</h3>
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Total</th>
                    <th>With Results</th>
                    <th>Success Rate</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
    </div>
    '''


def generate_failure_analysis(failure_data):
    """Generate failure analysis section."""
    if not failure_data:
        return ""
    
    samples = ""
    for job in failure_data.get('sample_incomplete', [])[:5]:
        samples += f'''
        <tr>
            <td>{job.get('job_name', 'unknown')}</td>
            <td>{job.get('job_type', 'unknown')}</td>
            <td>{job.get('model_size', 'unknown')}</td>
            <td>{job.get('file', 'unknown')}</td>
        </tr>
        '''
    
    return f'''
    <h2>⚠️ Failure Analysis</h2>
    <div class="card">
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value warning">{failure_data.get('incomplete_count', 0)}</div>
                <div class="stat-label">Incomplete Jobs</div>
            </div>
            <div class="stat-card">
                <div class="stat-value danger">{failure_data.get('no_end_time_count', 0)}</div>
                <div class="stat-label">No End Time</div>
            </div>
        </div>
        
        <h3>Sample Incomplete Jobs</h3>
        <table>
            <thead>
                <tr>
                    <th>Job Name</th>
                    <th>Type</th>
                    <th>Model</th>
                    <th>File</th>
                </tr>
            </thead>
            <tbody>{samples}</tbody>
        </table>
    </div>
    '''


def generate_html_report(analysis_dir, output_file):
    """Generate complete HTML report from analysis results."""
    
    # Load all analysis files
    all_logs = load_json_file(os.path.join(analysis_dir, 'all_logs_data.json'))
    monthly = load_json_file(os.path.join(analysis_dir, 'monthly_analysis.json'))
    job_types = load_json_file(os.path.join(analysis_dir, 'job_type_analysis.json'))
    pretrain = load_json_file(os.path.join(analysis_dir, 'pretrain_detailed.json'))
    eval_results = load_json_file(os.path.join(analysis_dir, 'eval_results.json'))
    failures = load_json_file(os.path.join(analysis_dir, 'failure_analysis.json'))
    
    # Generate content sections
    content = ""
    content += generate_stats_cards(all_logs)
    content += generate_monthly_chart(monthly)
    content += generate_job_type_table(job_types)
    content += generate_model_size_chart(job_types)
    content += generate_pretrain_analysis(pretrain)
    content += generate_eval_analysis(eval_results)
    content += generate_failure_analysis(failures)
    
    # Generate final HTML
    html = HTML_TEMPLATE.format(
        generated_date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        content=content
    )
    
    with open(output_file, 'w') as f:
        f.write(html)
    
    print(f"HTML report saved to: {output_file}")


def main():
    parser = argparse.ArgumentParser(description='Generate HTML visualization report')
    parser.add_argument('--input', '-i', default='analysis_output',
                       help='Directory containing analysis JSON files')
    parser.add_argument('--output', '-o', default='log_analysis_report.html',
                       help='Output HTML file')
    
    args = parser.parse_args()
    
    generate_html_report(args.input, args.output)


if __name__ == '__main__':
    main()
